#!/bin/bash
python3 gen2.py pybv build headers.txt
g++ -shared -rdynamic -g -O3 -Wall -fPIC bv.cpp src/wrapper.cpp -DMODULE_STR=bv -DMODULE_PREFIX=pybv -DNDEBUG -DPY_MAJOR_VERSION=3 `pkg-config --cflags --libs opencv` `python3-config --includes --ldflags` -I . -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -o build/bv.so